news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsdb.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsdb/urls.py
from django.urls import path

from . import views

app_name = 'newsdb'
urlpatterns = [
    path('', views.NewsList.as_view(), name='news_list'),
    path('<int:pk>/', views.NewsDetail.as_view(), name='news_detail'),
    path('tag/<str:tag_name>/', views.NewsByTag.as_view(), name='news_by_tag'),
]

newsdb/models.py
from django.db import models


NEWS_IMGS_FOLDER = 'news_images/'
DEF_NEWS_IMG = NEWS_IMGS_FOLDER + 'default.png'


class SingleNews(models.Model):
    heading = models.CharField(max_length=64)
    text = models.TextField()
    image = models.ImageField(
        upload_to=NEWS_IMGS_FOLDER,
        default=DEF_NEWS_IMG
    )
    tags = models.ManyToManyField('NewsTag', blank=True)

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name_plural = 'News'


class NewsTag(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

newsdb/views.py
from django.views import generic

from .models import SingleNews


class NewsList(generic.ListView):
    template_name = 'newsdb/news_list.html'
    model = SingleNews


class NewsDetail(generic.DetailView):
    template_name = 'newsdb/news_detail.html'
    model = SingleNews


class NewsByTag(NewsList):

    def get_queryset(self):
        """
        Return News which have the specified tag.
        """
        tag_name = self.kwargs['tag_name']
        return self.model.objects.filter(tags__name=tag_name)

    def get_context_data(self, **kwargs):
        """
        Set page_title using tag.
        """
        context = super().get_context_data(**kwargs)
        context['page_title'] = "All news by tag: " + self.kwargs['tag_name']
        return context

newsdb/templates/newsdb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}
    {% endblock %}
  </title>
</head>
<body>
  <h1>
    <a href="{% url 'newsdb:news_list' %}">
      <span>All News</span>
    </a>
  </h1>
  {% block content %}
  {% endblock %}
</body>
</html>

newsdb/templates/newsdb/news_detail.html
{% extends 'newsdb/base.html' %}
{% block title %}
  {{ singlenews.heading }}
{% endblock %}
{% block content %}
  <div class="news">
    <div class="heading">
      {{ news.heading }}
    </div>
    <div class="image">
      <img src="{{ singlenews.image.url }}" alt="{{ singlenews.heading }}">
    </div>
    {% include 'newsdb/news_tags.html' with news=singlenews %}
    <div class="news-text">
      {{ singlenews.text }}
    </div>
  </div>
{% endblock %}

newsdb/templates/newsdb/news_list.html
{% extends 'newsdb/base.html' %}
{% block title %}
  {{ page_title | default:"All News" }}
{% endblock %}
{% block content %}
  {% for news in singlenews_list %}
    <div class="news">
      <div class="heading">
        <a href="{% url 'newsdb:news_detail' news.id %}">
          {{ news.heading }}
        </a>
      </div>
      {% include 'newsdb/news_tags.html' %}
    </div>
  {% empty %}
    <div>No news...</div>
  {% endfor %}
{% endblock %}

newsdb/templates/newsdb/news_tags.html
<div class="tags">
  Tags:
  {% for tag in news.tags.all %}
    <a href="{% url 'newsdb:news_by_tag' tag.name %}">
      <span>
        {{ tag.name }}
      </span>
    </a>
  {% empty %}
    <span>
      None
    </span>
  {% endfor %}
</div>